{% set name = "AmpForm" %}
{% set version = "0.11.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 60813a1a9954c4fce48d3d0888fc81340eba8859803590d4cbd02f0f9abaf807

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - setuptools_scm
  run:
    - python >=3.6,<3.10
    - attrs >=20.1.0
    - qrules ==0.9.*
    - numpy >=1.16,<1.21
    - sympy
    - typing-extensions

test:
  imports:
    - ampform
    - ampform.data
    - ampform.dynamics
    - ampform.helicity
    - ampform.kinematics

about:
  home: https://github.com/ComPWA/ampform
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Automatically generate symbolic amplitude models for Partial Wave Analysis

  description: |
    AmpForm is a Python library of spin formalisms and dynamics with which you can
    automatically formulate symbolic amplitude models for Partial Wave Analysis.
    The resulting amplitude models are formulated with
    [SymPy](https://www.sympy.org/en/index.html). This note only makes it easy to
    inspect and visualize the resulting amplitude models, but also means the
    amplitude models can be used as templates for faster computational back-ends
    (see [TensorWaves](https://github.com/ComPWA/tensorwaves))!


  dev_url: https://github.com/ComPWA/ampform
  doc_url: https://ampform.readthedocs.io

extra:
  recipe-maintainers:
    - redeboer
