{% set name = "AmpForm" %}
{% set version = "0.14.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: dba2da80abb2146c4f732ccc96fc28fb1428b12c4d66b78abbf1dc218f07df29

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - python >=3.7
    - attrs >=20.1.0
    - importlib-metadata
    - qrules >=0.9.6
    - singledispatchmethod
    - sympy >=1.10
    - typing-extensions

test:
  imports:
    - ampform
    - ampform.dynamics
    - ampform.helicity
    - ampform.io
    - ampform.kinematics
    - ampform.sympy

about:
  home: https://github.com/ComPWA/ampform
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Automatically generate symbolic amplitude models for Partial Wave Analysis

  description: |
    AmpForm is a Python library of spin formalisms and dynamics with which you can
    automatically formulate symbolic amplitude models for Partial Wave Analysis.
    The resulting amplitude models are formulated with
    [SymPy](https://www.sympy.org/en/index.html). This note only makes it easy to
    inspect and visualize the resulting amplitude models, but also means the
    amplitude models can be used as templates for faster computational back-ends
    (see [TensorWaves](https://github.com/ComPWA/tensorwaves))!


  dev_url: https://github.com/ComPWA/ampform
  doc_url: https://ampform.readthedocs.io

extra:
  recipe-maintainers:
    - redeboer
