{% set name = "ampform" %}
{% set version = "0.15.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ampform-{{ version }}.tar.gz
  sha256: 05eaf118bb5f77bc3c0595cceeb226dbe717b8d5ab69fe40cca139fe6ed52d2a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - attrs >=20.1.0
    - qrules >=0.9.6
    - sympy >=1.10

test:
  imports:
    - ampform
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  description: |
    AmpForm is a Python library of spin formalisms and dynamics with which you can
    automatically formulate symbolic amplitude models for Partial Wave Analysis.
    The resulting amplitude models are formulated with
    [SymPy](https://www.sympy.org/en/index.html). This note only makes it easy to
    inspect and visualize the resulting amplitude models, but also means the
    amplitude models can be used as templates for faster computational back-ends
    (see [TensorWaves](https://github.com/ComPWA/tensorwaves)).
  dev_url: https://github.com/ComPWA/ampform
  doc_url: https://ampform.readthedocs.io
  home: https://github.com/ComPWA/ampform
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Automatically generate symbolic amplitude models for Partial Wave Analysis

extra:
  recipe-maintainers:
    - redeboer
    - shenvitor
